"""Deterministic activation capture manifests."""

from .activations import (
    activation_partition_deterministic,
    capture_activation_shards,
    capture_activations,
    capture_multi_layer_activation_shards,
    iter_activation_shards,
)
from .teacher import (
    REPRESENTATIVE_LAYERS,
    HookVerification,
    TeacherCaptureBlocked,
    TokenizedExample,
    capture_native_teacher,
    capture_native_teacher_activations,
    capture_teacher_activations,
    capture_text_teacher_activations,
    discover_mlp_modules,
    discover_mlp_paths,
    discover_torch_devices,
    fixed_split_metadata,
    is_pinned_source_revision,
    live_resource_snapshot,
    load_native_teacher,
    load_pinned_tokenizer,
    resolve_corpus_records,
    resource_aware_max_memory,
    snapshot_tokenizer_hashes,
    tokenize_corpus_records,
    validate_mlp_hook,
    verify_mlp_reconstruction,
)

__all__ = [
    "REPRESENTATIVE_LAYERS",
    "HookVerification",
    "TeacherCaptureBlocked",
    "TokenizedExample",
    "activation_partition_deterministic",
    "capture_activation_shards",
    "capture_activations",
    "capture_multi_layer_activation_shards",
    "capture_native_teacher",
    "capture_native_teacher_activations",
    "capture_teacher_activations",
    "capture_text_teacher_activations",
    "discover_mlp_modules",
    "discover_mlp_paths",
    "discover_torch_devices",
    "fixed_split_metadata",
    "is_pinned_source_revision",
    "iter_activation_shards",
    "live_resource_snapshot",
    "load_native_teacher",
    "load_pinned_tokenizer",
    "resolve_corpus_records",
    "resource_aware_max_memory",
    "snapshot_tokenizer_hashes",
    "tokenize_corpus_records",
    "validate_mlp_hook",
    "verify_mlp_reconstruction",
]
