"""Exact FFN neuron partitioning and deterministic activation assignment."""

from .ffn import (
    ActivationPartitioner,
    PartitionPlan,
    balanced_signature_partition,
    pack_experts,
    partition_ffn_weights,
    partition_indices,
    reconstruct_ffn_weights,
    unpack_experts,
)
from .oracle import (
    frozen_slice_load_aware_oracle,
    frozen_slice_positive_oracle,
    frozen_slice_scaled_router_oracle,
    frozen_slice_simplex_oracle,
    load_aware_oracle,
    load_constrained_oracle,
    oracle_topk,
    sparse_baseline,
    swiglu_contributions,
    trainable_student_proxy,
)
from .contributions import (
    basis_outputs_from_state,
    canonical_partition_sha256,
    contribution_manifest,
    load_partition_plan,
    load_trained_basis_state,
    raw_dense_partition_contributions,
    reconstruct_selected,
    resolve_checkpoint_tensor,
    sha256_file,
    trained_checkpoint_contributions,
)

__all__ = [
    "ActivationPartitioner",
    "PartitionPlan",
    "balanced_signature_partition",
    "frozen_slice_load_aware_oracle",
    "frozen_slice_positive_oracle",
    "frozen_slice_scaled_router_oracle",
    "frozen_slice_simplex_oracle",
    "load_aware_oracle",
    "load_constrained_oracle",
    "oracle_topk",
    "pack_experts",
    "partition_ffn_weights",
    "partition_indices",
    "reconstruct_ffn_weights",
    "sparse_baseline",
    "swiglu_contributions",
    "trainable_student_proxy",
    "unpack_experts",
    "basis_outputs_from_state",
    "canonical_partition_sha256",
    "contribution_manifest",
    "load_partition_plan",
    "load_trained_basis_state",
    "raw_dense_partition_contributions",
    "reconstruct_selected",
    "resolve_checkpoint_tensor",
    "sha256_file",
    "trained_checkpoint_contributions",
]
